services:
  - type: web
    name: calls-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:arkon08_trello%23jg%249@db.lqdcrnxrqzccismdrwwb.supabase.co:5432/postgres
      - key: AMOCRM_DOMAIN
        value: numbersarkon.amocrm.ru
      - key: AMOCRM_TOKEN
        sync: false

  - type: static
    name: calls-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/*
        destination: https://calls-backend.onrender.com/api/*
