name: qongiroklar-holati
region: fra

ingress:
  rules:
    - component:
        name: backend
      match:
        path:
          prefix: /api
    - component:
        name: frontend
      match:
        path:
          prefix: /

services:
  - name: backend
    source_dir: /backend
    github:
      repo: sotimovjahongir139-create/tells
      branch: main
      deploy_on_push: true
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3000
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ""          # set in DO dashboard: postgresql://postgres.ID:PASS@pooler.supabase.com:5432/postgres
      - key: AMOCRM_DOMAIN
        scope: RUN_TIME
        value: numbersarkon.amocrm.ru
      - key: AMOCRM_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: ""          # set in DO dashboard

static_sites:
  - name: frontend
    source_dir: /frontend
    github:
      repo: sotimovjahongir139-create/tells
      branch: main
      deploy_on_push: true
    environment_slug: html
